# Generated by Django 5.2.8 on 2026-01-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='sender',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
